**이직여부 판단 데이터**
===

Attention
===

데이터 설명 : 이직여부 판단 데이터 (target: 1: 이직 , 0 : 이직 x)   
x_train: https://raw.githubusercontent.com/Datamanim/datarepo/main/HRdata/X_train.csv   
y_train: https://raw.githubusercontent.com/Datamanim/datarepo/main/HRdata/y_train.csv   
x_test: https://raw.githubusercontent.com/Datamanim/datarepo/main/HRdata/X_test.csv   
x_label(평가용) : https://raw.githubusercontent.com/Datamanim/datarepo/main/HRdata/y_test.csv   
데이터 출처 :https://www.kaggle.com/datasets/arashnic/hr-analytics-job-change-of-data-scientists (참고, 데이터 수정)

In [1]:
import pandas as pd
#데이터 로드
x_train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/HRdata/X_train.csv")
y_train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/HRdata/y_train.csv")
x_test= pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/HRdata/X_test.csv")


display(x_train.head())
display(y_train.head())

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
0,25298,city_138,0.836,Male,No relevent experience,Full time course,High School,NaN,5,100-500,Pvt Ltd,1,45
1,4241,city_160,0.920,Male,No relevent experience,Full time course,High School,NaN,5,NaN,NaN,1,17
2,24086,city_57,0.866,Male,No relevent experience,no_enrollment,Graduate,STEM,10,NaN,NaN,1,50
3,26773,city_16,0.910,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,>4,135
4,32325,city_143,0.740,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,17

   enrollee_id  target
0        25298     0.0
1         4241     1.0
2        24086     0.0
3        26773     0.0
4        32325     1.0

In [7]:
# 결측치가 있지만 따로 처리하지 않고 더미화 ? 왜 ?
print(x_train.info())
print(x_train.nunique())
print(x_train.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12452 entries, 0 to 12451
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             12452 non-null  int64
 1   city                    12452 non-null  object
 2   city_development_index  12452 non-null  float64
 3   gender                  9535 non-null   object
 4   relevent_experience     12452 non-null  object
 5   enrolled_university     12195 non-null  object
 6   education_level         12137 non-null  object
 7   major_discipline        10586 non-null  object
 8   experience              12415 non-null  object
 9   company_size            8600 non-null   object
 10  company_type            8471 non-null   object
 11  last_new_job            12179 non-null  object
 12  training_hours          12452 non-null  int64
dtypes: float64(1), int64(2), object(10)
memory usage: 1.2+ MB
None
enrollee_id               12452
city                        122
city_development_index       92
gender                        3
relevent_experience           2
enrolled_university           3
education_level               5
major_discipline              6
experience                   22
company_size                  8
company_type                  6
last_new_job                  6
training_hours              241
dtype: int64
enrollee_id                  0
city                         0
city_development_index       0
gender                    2917
relevent_experience          0
enrolled_university        257
education_level            315
major_discipline          1866
experience                  37
company_size              3852
company_type              3981
last_new_job               273
training_hours               0
dtype: int64

In [14]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6706 entries, 0 to 6705
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             6706 non-null   int64
 1   city                    6706 non-null   object
 2   city_development_index  6706 non-null   float64
 3   gender                  5115 non-null   object
 4   relevent_experience     6706 non-null   object
 5   enrolled_university     6577 non-null   object
 6   education_level         6561 non-null   object
 7   major_discipline        5759 non-null   object
 8   experience              6678 non-null   object
 9   company_size            4620 non-null   object
 10  company_type            4547 non-null   object
 11  last_new_job            6556 non-null   object
 12  training_hours          6706 non-null   int64
dtypes: float64(1), int64(2), object(10)
memory usage: 681.2+ KB

In [34]:
# 범주형 변수이면서, 적당히 많은 unique값을 가진 컬럼은 날린다.
# drop_col = ['enrollee_id', 'city', 'city_development_index', 'experience', 'training_hours'] 
## -> 학습 결과 꽝..
drop_col = ['enrollee_id','city','company_type','experience']
x_train_drop = x_train.drop(columns = drop_col)
x_test_drop = x_test.drop(columns = drop_col)

In [35]:
import sklearn
print(sklearn.__all__)
import sklearn.model_selection
print(dir(sklearn.model_selection))

print(dir(sklearn.ensemble))

['calibration', 'cluster', 'covariance', 'cross_decomposition', 'datasets', 'decomposition', 'dummy', 'ensemble', 'exceptions', 'experimental', 'externals', 'feature_extraction', 'feature_selection', 'gaussian_process', 'inspection', 'isotonic', 'kernel_approximation', 'kernel_ridge', 'linear_model', 'manifold', 'metrics', 'mixture', 'model_selection', 'multiclass', 'multioutput', 'naive_bayes', 'neighbors', 'neural_network', 'pipeline', 'preprocessing', 'random_projection', 'semi_supervised', 'svm', 'tree', 'discriminant_analysis', 'impute', 'compose', 'clone', 'get_config', 'set_config', 'config_context', 'show_versions']
['BaseCrossValidator', 'BaseShuffleSplit', 'GridSearchCV', 'GroupKFold', 'GroupShuffleSplit', 'KFold', 'LearningCurveDisplay', 'LeaveOneGroupOut', 'LeaveOneOut', 'LeavePGroupsOut', 'LeavePOut', 'ParameterGrid', 'ParameterSampler', 'PredefinedSplit', 'RandomizedSearchCV', 'RepeatedKFold', 'RepeatedStratifiedKFold', 'ShuffleSplit', 'StratifiedGroupKFold', 'StratifiedKFold', 'StratifiedShuffleSplit', 'TimeSeriesSplit', 'ValidationCurveDisplay', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_plot', '_search', '_split', '_validation', 'check_cv', 'cross_val_predict', 'cross_val_score', 'cross_validate', 'learning_curve', 'permutation_test_score', 'train_test_split', 'typing', 'validation_curve']
['AdaBoostClassifier', 'AdaBoostRegressor', 'BaggingClassifier', 'BaggingRegressor', 'BaseEnsemble', 'ExtraTreesClassifier', 'ExtraTreesRegressor', 'GradientBoostingClassifier', 'GradientBoostingRegressor', 'HistGradientBoostingClassifier', 'HistGradientBoostingRegressor', 'IsolationForest', 'RandomForestClassifier', 'RandomForestRegressor', 'RandomTreesEmbedding', 'StackingClassifier', 'StackingRegressor', 'VotingClassifier', 'VotingRegressor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bagging', '_base', '_forest', '_gb', '_gb_losses', '_gradient_boosting', '_hist_gradient_boosting', '_iforest', '_stacking', '_voting', '_weight_boosting']

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

x_train_dummies = pd.get_dummies(x_train_drop)
y = y_train['target'].astype('int')

x_test_dummies = pd.get_dummies(x_test_drop)
# train과 컬럼 순서 동일하게 하기 (더미화하면서 순서대로 정렬을 이미 하기 때문에 오류가 난다면 해당 컬럼이 누락된 것.)
x_test_dummies = x_test_dummies[x_train_dummies.columns]
# print(help(train_test_split))

# 훈련 셋, 테스트 셋 분리
X_train, X_validation, Y_train, Y_validation = train_test_split(x_train_dummies, y, test_size=0.33, random_state=42)
# 모델 선정
rf = RandomForestClassifier(random_state=23)
# 모델 학습..
rf.fit(X_train, Y_train)

RandomForestClassifier(random_state=23)

In [37]:
import sklearn.metrics
print(dir(sklearn.metrics))

['ConfusionMatrixDisplay', 'DetCurveDisplay', 'DistanceMetric', 'PrecisionRecallDisplay', 'PredictionErrorDisplay', 'RocCurveDisplay', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_base', '_classification', '_dist_metrics', '_pairwise_distances_reduction', '_pairwise_fast', '_plot', '_ranking', '_regression', '_scorer', 'accuracy_score', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'auc', 'average_precision_score', 'balanced_accuracy_score', 'brier_score_loss', 'calinski_harabasz_score', 'check_scoring', 'class_likelihood_ratios', 'classification_report', 'cluster', 'cohen_kappa_score', 'completeness_score', 'confusion_matrix', 'consensus_score', 'coverage_error', 'd2_absolute_error_score', 'd2_pinball_score', 'd2_tweedie_score', 'davies_bouldin_score', 'dcg_score', 'det_curve', 'euclidean_distances', 'explained_variance_score', 'f1_score', 'fbeta_score', 'fowlkes_mallows_score', 'get_scorer', 'get_scorer_names', 'hamming_loss', 'hinge_loss', 'homogeneity_completeness_v_measure', 'homogeneity_score', 'jaccard_score', 'label_ranking_average_precision_score', 'label_ranking_loss', 'log_loss', 'make_scorer', 'matthews_corrcoef', 'max_error', 'mean_absolute_error', 'mean_absolute_percentage_error', 'mean_gamma_deviance', 'mean_pinball_loss', 'mean_poisson_deviance', 'mean_squared_error', 'mean_squared_log_error', 'mean_tweedie_deviance', 'median_absolute_error', 'multilabel_confusion_matrix', 'mutual_info_score', 'nan_euclidean_distances', 'ndcg_score', 'normalized_mutual_info_score', 'pair_confusion_matrix', 'pairwise', 'pairwise_distances', 'pairwise_distances_argmin', 'pairwise_distances_argmin_min', 'pairwise_distances_chunked', 'pairwise_kernels', 'precision_recall_curve', 'precision_recall_fscore_support', 'precision_score', 'r2_score', 'rand_score', 'recall_score', 'roc_auc_score', 'roc_curve', 'silhouette_samples', 'silhouette_score', 'top_k_accuracy_score', 'v_measure_score', 'zero_one_loss']

In [38]:
from sklearn.metrics import accuracy_score, f1_score, recall_score, roc_auc_score, precision_score

# model score
predict_train_label = rf.predict(X_train)
predict_train_proba = rf.predict_proba(X_train)[:,1]

predict_validation_label = rf.predict(X_validation)
predict_validation_proba = rf.predict_proba(X_validation)[:,1]

# 문제에서 묻는 것에 따라 모델 성능 확인하기
# 정확도 (accuracy) , f1_score , recall , precision -> model.predict로 결과뽑기
# auc , 확률이라는 표현있으면 model.predict_proba로 결과뽑고 첫번째 행의 값을 가져오기 model.predict_proba()[:,1]

# train -> 학습 셋 
# validation -> 테스트 셋

print('train accracy : ', accuracy_score(Y_train, predict_train_label))
print('validation accuracy : ', accuracy_score(Y_validation, predict_validation_label))
print('\n')

print('train f1_score : ', f1_score(Y_train, predict_train_label))
print('validation f1_score : ', f1_score(Y_validation, predict_validation_label))
print('\n')

print('train recall_score : ', recall_score(Y_train, predict_train_label))
print('validation recall_score : ', recall_score(Y_validation, predict_validation_label))
print('\n')

print('train precision_score : ', precision_score(Y_train, predict_train_label))
print('validation precision_score : ', precision_score(Y_validation, predict_validation_label))
print('\n')

print('train auc : ', roc_auc_score(Y_train, predict_train_proba))
print('validation auc : ', roc_auc_score(Y_validation, predict_validation_proba))

train accracy :  0.9965236154399425
validation accuracy :  0.7535279805352798


train f1_score :  0.9929731039496001
validation f1_score :  0.42736009044657997


train recall_score :  0.9927325581395349
validation recall_score :  0.3631123919308357


train precision_score :  0.9932137663596704
validation precision_score :  0.5192307692307693


train auc :  0.9998907607098495
validation auc :  0.740677513569584

In [39]:
predict_test_label = rf.predict(x_test_dummies)
predict_test_proba = rf.predict_proba(x_test_dummies)[:, 1]

pd.DataFrame({'emrollee_id': x_test.enrollee_id, 'target': predict_test_label})
# pd.DataFrame({'emrollee_id': x_test.enrollee_id, 'target': predict_test_proba}).to_csv('수험번호.csv',index=False)
pd.DataFrame({'emrollee_id': x_test.enrollee_id, 'target': predict_test_label})
# pd.DataFrame({'emrollee_id': x_test.enrollee_id, 'target': predict_test_proba}).to_csv('수험번호.csv', index=False)

      emrollee_id  target
0            7129       0
1           31037       0
2           22179       0
3           29724       0
4           17977       0
...           ...     ...
6701         3601       0
6702         2745       0
6703        18520       0
6704        10067       0
6705         8203       1

[6706 rows x 2 columns]